/* Smoke test for Madison Dev Tracker v1.2 (open, 3-stage flow). Run: node smoke-test.js (server must be running) */
const BASE = 'http://localhost:3100';
async function req(p, opt = {}) {
  const r = await fetch(BASE + p, { headers: { 'Content-Type': 'application/json' }, ...opt });
  let j = null; try { j = await r.json(); } catch (e) { /* non-json */ }
  return { status: r.status, body: j };
}
const assert = (c, m) => { if (!c) { console.error('FAIL:', m); process.exitCode = 1; } else console.log('ok:', m); };
(async () => {
  let r = await req('/api/meta');
  assert(JSON.stringify(r.body.statuses) === JSON.stringify(['Pipeline', 'Development', 'UAT', 'Live', 'On Hold']), 'meta = 5 stages');
  r = await req('/api/systems');
  assert(r.body.length >= 1 && r.body.every(s => s.color), r.body.length + ' systems with colors');
  const systemId = r.body[0].id;
  r = await req('/api/tasks');
  assert(r.status === 200 && r.body.length >= 12, 'open access, ' + r.body.length + ' tasks');
  assert(r.body.every(t => ['Pipeline', 'Development', 'UAT', 'Live', 'On Hold'].includes(t.status)), 'all statuses migrated to 5 stages');
  r = await req('/api/tasks', { method: 'POST', body: JSON.stringify({ title: 'Smoke ticket', systemId }) });
  assert(r.status === 201 && r.body.status === 'Pipeline', 'new ticket defaults to Pipeline');
  const id = r.body.id;
  r = await req('/api/tasks/' + id, { method: 'PATCH', body: JSON.stringify({ status: 'Development' }) });
  assert(r.body.status === 'Development', 'move Pipeline -> Development');
  r = await req('/api/tasks/' + id, { method: 'PATCH', body: JSON.stringify({ status: 'UAT' }) });
  assert(r.body.status === 'UAT', 'move Development -> UAT');
  r = await req('/api/tasks/' + id, { method: 'PATCH', body: JSON.stringify({ status: 'Live' }) });
  assert(r.body.status === 'Live', 'move UAT -> Live');
  r = await req('/api/tasks/' + id, { method: 'PATCH', body: JSON.stringify({ status: 'On Hold' }) });
  assert(r.body.status === 'On Hold', 'move Live -> On Hold');
  r = await req('/api/tasks/' + id, { method: 'DELETE' });
  assert(r.status === 200, 'delete ok');
  r = await req('/api/stats');
  assert(r.body.total >= 12 && (r.body.byStatus['Live'] || 0) >= 1 && typeof r.body.overdue === 'number', 'stats consistent + overdue');
  r = await req('/api/projects');
  assert(r.status === 200 && r.body.length >= 12 && r.body.every(p => typeof p.pct === 'number' && p.byStage), 'projects derived with progress + stages');
  const prj = r.body.find(p => p.total > 0) || r.body[0];
  assert(prj.benefits && prj.benefitsCalc && prj.benefitsCalc.fteHoursPerMonth === 160, 'projects expose policy-based benefits calculation');
  r = await req('/api/projects/' + prj.id, { method: 'PATCH', body: JSON.stringify({ benefits: { currentHandlingMinutes: 12, transactionsPerMonth: 3000, futureHandlingMinutes: 2, futureManualHoursPerMonth: 100, annualCostPerFte: 900000 } }) });
  assert(r.status === 200, 'save project benefits baseline');
  r = await req('/api/projects');
  const calc = r.body.find(p => p.id === prj.id).benefitsCalc;
  assert(calc.timeSaved === 500 && calc.fteEquivalent === 3.13 && calc.costAvoidance === 2812500, 'benefits math: 600 baseline - 100 future = 500 hours');
  r = await req('/api/benefits');
  assert(r.status === 200 && r.body.some(x => x.projectId === prj.id && x.calculation.timeSaved === 500), 'benefits endpoint links calculation to project');
  await req('/api/projects/' + prj.id, { method: 'PATCH', body: JSON.stringify({ benefits: {} }) });
  r = await req('/api/subprojects', { method: 'POST', body: JSON.stringify({ projectId: prj.id, name: 'Smoke sub' }) });
  assert(r.status === 201, 'create sub-project');
  const sid = r.body.id;
  const tk = (await req('/api/tasks')).body[0];
  r = await req('/api/tasks/' + tk.id, { method: 'PATCH', body: JSON.stringify({ subprojectId: sid }) });
  assert(r.status === 200, 'link ticket to sub-project');
  r = await req('/api/projects');
  assert(r.body.find(p => p.id === prj.id).subprojects.some(s=>s.id===sid), 'sub-project nested in project');
  r = await req('/api/subprojects/' + sid, { method: 'DELETE' });
  assert(r.status === 200, 'delete sub-project');
  r = await req('/api/tasks', { method: 'POST', body: JSON.stringify({ systemId: 'SYS-HQ' }) });
  assert(r.status === 400, 'task validation (400, no title)');
  r = await req('/api/tasks/T-NOPE', { method: 'PATCH', body: JSON.stringify({ status: 'Completed' }) });
  assert(r.status === 404, 'unknown ticket (404)');
  r = await req('/api/projects', { method: 'POST', body: JSON.stringify({ name: 'x' }) });
  assert(r.status === 400, 'project validation (400, no systemId)');
  r = await req('/api/subprojects', { method: 'POST', body: JSON.stringify({ name: 'x', projectId: 'PRJ-NOPE' }) });
  assert(r.status === 400, 'sub-project validation (400, unknown project)');
  r = await req('/api/sync/push?dry=1', { method: 'POST' });
  assert(r.status === 200 && r.body.ok === true && Array.isArray(r.body.added), 'push dry-run (zero writes)');
  r = await req('/api/sync/status');
  assert(r.status === 200 && 'pull' in r.body && 'push' in r.body, 'sync status shape');
  r = await req('/api/export');
  assert(r.status === 200 && Array.isArray(r.body.projects) && Array.isArray(r.body.subprojects), 'export includes projects + sub-projects');
  r = await req('/api/projects', { method: 'POST', body: JSON.stringify({ name: 'x', systemId: 'SYS-NOPE' }) });
  assert(r.status === 400, 'project validation (unknown system)');
  r = await req('/api/tasks', { method: 'POST', body: JSON.stringify({ title: 'x', systemId: 'SYS-NOPE' }) });
  assert(r.status === 400, 'task validation (unknown system)');
  console.log('SMOKE DONE');
})();
